### ISSUE TITLE
Create an ActBlue class / connector

### ISSUE THREAD

**Issue by joemcl** [move-coop/parsons#121]
See this, to start - https://secure.actblue.com/docs/webhooks

**Comment by eliotst** [comment]
Adding functionality to parsons to allow users to access ActBlue data would be great, but there's no way to do it. Parsons connector classes are written to be able to **ASK** an API for data using a request/response model. ActBlue's webhooks don't provide that kind of API. To get data from ActBlue, you have to configure your account so that ActBlue can **SEND** data to you using a publish/subscribe model.

In order to receive the data that ActBlue is sending, you have to set up a web application that ActBlue can access over the internet. Parsons is a library meant to be used by applications, and is not an application in and of itself. There are frameworks for building web applications like this, but these are a different category of software from parsons.

**Comment by joemcl** [comment]
Huh. So in theory could ActBlue just add an **ASK** capability to its webhooks?

**Comment by jburchard** [comment]
@joemcl - We've got some other potential ideas outside of Parsons as to how we could think about this. Definitely agree that this is a need. I'm going to close this issue for the time being.
