### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by schuyler1d** [move-coop/parsons#146]
The current pattern in `parsons` is to load every submodule into `parsons/__init__.py`.

This is neither sustainable nor feasible for systems that require smaller upload sizes/memory footprints (e.g. AWS Lambda).  The top of that file makes the goal clear:
"Eg. This allows for: `from parsons import VAN`"
However, it means every install and deploy of parsons requires an ever-increasing number of dependencies.

Proposal:
* Remove the pre-amble -- or at least stop adding new ones.  Admittedly this is backwards incompatible
  * If we must keep backwards incompatibility, then let's create a second lib called `parsons_core` where we move the sub-directories, and then import them in `parsons/` from parsons_core.
* Start documenting the best practice of importing `from parsons_core.nvpvan import VAN`
* Document for low environments that they can install/import with `pip install --no-deps parsons` -- maintain a requirements-core.txt for cross-source dependencies that can/should stay in core.

**Comment by eliotst** [comment]
This is great feedback, thanks!

I think I understand your concerns. One of the challenges for us is making Parsons as accessible as we can, which can mean sometimes something as trivial as not expecting all of our users to totally understand Python imports. We have broad range of skillsets in our user base, so we are looking to balance the different needs of the community. That being said, this is a tension that we are constantly trying to work through, and we are glad to have the community involved in this conversation.

I appreciate your proposed solutions. I will work with our engineering team to try to update our documents to include best practices for lower resource environments. We will start with suggesting users directly import from the specific Python modules where the classes are defined. Also, we can document your `--no-deps` solution, and talk through how to selectively install dependencies. I think that for now, we can do all of this without making changes to the existing Parsons package structure.

If you want, I can tag you on the Pull Request for the document changes, since we would appreciate any feedback you might have on the changes. Let me know!
