### ISSUE TITLE
Box Connector v1

### ISSUE THREAD

**Issue by jburchard** [move-coop/parsons#217]
This would serve as the initial connector for interacting with the Box API. There is a [robust SDK](https://github.com/box/box-python-sdk) that might be a good starting point.

- List folders
- List files
- Get file
- Save file to box

**Comment by SorenSpicknall** [comment]
For anybody who wants to pick it up, I started a branch for these changes here: https://github.com/move-coop/parsons/tree/box_connector

**Comment by shaunagm** [comment]
We did a little more work on the box connector.  Rather than putting it on a branch, I'll just summarize here.  Feel free to copy & paste onto Soren's branch or make your own.

Step 1: Setting up imports

To make the imports work, in addition to adding the `__init__.py` in the box folder, you also have to add the reference in the `parsons/__init__.py`, specifically you'll need to add `from parsons.box.box import Box` after all the other imports and then add 'Box' in the list `__all__`.  Actually this should be part of the How To Build A Connector docs, too.

Step 2: Authenticating

Some info on getting your authentication info, which eventually belongs in the docs for this connector. After you make a free box account, go to developer console, create a new app or select an existing app and click through to that app's page, and then click configuration on the left hand sidebar.  Scroll down to get the client id & secret, and just above it you can generate a developer token, aka "access token".

Step 3: List Files

Here's our code for the list_files method:

```    def list_files(self, folder_id="0"):
        url = "https://api.box.com/2.0/folders/" + folder_id
        json_response = self.client.make_request('GET', url)
        return Table(json_response.json()["item_collection"]["entries"])
```

We were using the `get_files` method on the client at first but it was returning custom Python objects that were hard to reformat into a Parsons table.  Open question though whether we want to just use this endpoint of individually get the files by ID to get more information on each file.

**Comment by davidpablocohn** [comment]
I'm (finally!) getting started on this. I'm copying @SorenSpicknall's branch over to a local branch issue_217, then folding in @shaunagm's changes and using that as my starting point.

**Comment by davidpablocohn** [comment]
@jburchard - When getting a file, how much flexibility do you think is needed in which file formats can be gotten? get/put CSV is easy, but other formats turn out to have challenges because of a quirk of the lazy evaluation of Tables.*

*(Box lets you download a file to local, but you have to put it somewhere. If you use a Python tempfile, then Table chokes when the tempfile goes away. If you use a non temp file, you end up with stale files littering your filesystem. The only constructor that doesn't appear to rely on a file is `from_csv_string()`)
