### ISSUE TITLE
GitHub Connector

### ISSUE THREAD

**Issue by eliotst** [move-coop/parsons#229]
As the Parsons repository sees more usage and contributions, it would be great to be able to better report on things like outside contributions and automatically track progress on Parsons issues. To start, we would love to be able to pull down data about Pull Requests and Issues.

**Comment by shaunagm** [comment]
I've worked a little on this.

**Comment by pjsier** [comment]
I'm interested in trying this one out if it's available

**Comment by pjsier** [comment]
I took a quick look at other examples, and it looks like [PyGithub](https://github.com/PyGithub/PyGithub) is pretty well-maintained and seems to follow the same patterns as connectors here. Here's [an example from the docs](https://pygithub.readthedocs.io/en/latest/introduction.html) that uses `get_repo` and `get_user` in the same way I was thinking of implementing them.

PyGithub only has `pyjwt` and `requests` as dependencies, so adding it feels relatively safe. Is the best approach here to subclass it so that we can wrap how it sets the authentication credentials? I haven't worked a ton with Sphinx, but I'm guessing we could pull the documentation of methods in with `:inherited-members:` if we subclass it too

**Comment by pjsier** [comment]
I made an initial pass at this in my fork ([here's a diff](https://github.com/move-coop/parsons/compare/master...pjsier:feat/github-connector)) where I subclass PyGithub's main client and then decorate some the methods to make the output match Parsons more closely.

It feels a little unorthodox, but it also seems to work so far without introducing a lot of rework, and we can pick and choose the methods we want to implement. It looks like the only significant rework would be on documentation, since for any of the `search_X` methods we're adding a `page` keyword argument to handle PyGithub's paginated list object.

I can open a draft PR if that's easier to give feedback on, but it's still pretty early. Thanks!
