### ISSUE TITLE
Better SFTP 'helpers'

### ISSUE THREAD

**Issue by schuyler1d** [move-coop/parsons#248]
I have a few use-cases where some 'helper-ish' functions or restructuring in the SFTP driver would be useful.  Some use-cases:

* Using a connection for several steps at once (e.g. making create_connection() public and maybe each method takes an optional conn= argument)
* File and directory patterns -- instead of dir listing, then file listing, it would be nice to pass some regex patterns for a directory and file name, and then either download all files that match or at least list all the files that match.
* When downloading a file, sometimes there are some additional processing steps, but mostly after the steps, there's a CSV to turn into a table -- it would be nice to get a function (possibly with a lambda processing arg in-between), that downloads and returns the Table object straight-away

**Comment by eliotst** [comment]
Two of the three completed (1 and 3).

**Comment by tiburona** [comment]
@eliotst I could try to close out this issue by working on (2) if no one else is in progress on it.

**Comment by jburchard** [comment]
That would be great!

**Comment by tiburona** [comment]
As long as I'm in the `sftp` module, I'll note that `get_file` and `put_file` do not have the if/else structure I'd expect (and that other methods in the class do): 

```
if connection: 
    do something 
else: 
    with self.create_connection() as connection:
        do something else
```
 I can't tell whether this is an inconsequential bug or intentional for a reason I can't see.  If it is intentional, it would be nice to have a comment explaining it just so it doesn't distract future contributors.  I'd be happy to add it if I knew what it should say.
