### ISSUE TITLE
Determine method for getting Slack API Key

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#284]
Slack shutdown their legacy tokens, and it's unclear how one should generate an API key for use with the Slack class.

**Comment by shaunagm** [comment]
This is assigned to Soren - should it still be a Ragtag issue?

**Comment by elyse-weiss** [comment]
I will un-assign! Would love next available person!

**Comment by rgriff23** [comment]
I think I can take this on! So far I've followed steps to create and install a Slack App, which provides the API token. 

Within the Slack App, you must specify the 'scopes' that define your capabilities and permissions. For example, if I run `Slack().users()` using a token generated by an app that does not have the `users:read` scope enabled, I will get `SlackClientError: missing_scope`.

The different methods in the Parsons Slack class require different scopes, but it's a small fraction of the available scopes. So, it seems like the most important thing is to document which scopes you need to add to your Slack App in order to enable the Parsons class methods.
