### ISSUE TITLE
Unload Issues

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#322]
A few issues with the unload command:

- [ ] I was trying to run a query that ended with `where state='AK'` -- after some investigation by @eliotst, we discovered that I would need to write it as `where state=''AK''`, which is definitely not intuitive
- [ ] the data comes in pipe-delimited. This feels not ideal - slash would be great to be able to parameterize?
- [ ] the size limit meant I was producing A LOT of files - is there any way to up that?

**Comment by dannyboy15** [comment]
@elyse-weiss just submitted a PR that should help with the first 2 issues. For backwards compatibility and because Redshift uses the pipe (`|`) as their default delimiter, I left that as the default in the `unload` method.

This would work now:

```
rs.unload("select * from mytable where state='AK'", bucket, key_prefix, delimiter=",")
```

For the third point, the max file size is [already set to '6.2 GB'](https://github.com/move-coop/parsons/blob/master/parsons/databases/redshift/redshift.py#L525) which is the [max that Redshift allows](https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html#unload-maxfilesize). You can try setting `parallel=False` to force it to generate the files serially which would ensure that each file is `MAXFILESIZE` (unless there is not enough data).

```
rs.unload("select * from mytable where state='AK'", bucket, key_prefix, delimiter=",", parallel=False)
```

**Comment by elyse-weiss** [comment]
super helpful @dannyboy15 - thanks so much!
