### ISSUE TITLE
Airtable get_records column issue

### ISSUE THREAD

**Issue by mkwoods927** [move-coop/parsons#454]
On larger Airtable tables columns that are sparsely populated may get skipped in get_records unless sort is provided and the column is sorted descending.

The specific example came up in a table with 1,299 records where the column only had data in one record. When we tried to run get_records without any arguments the column doesn't come up in the returned Parsons Table. It also didn't come up when we provided a parameter for fields. Sorting by the column in descending order did work, and using a formula setting the column equal to the exact value worked as well.

We speculate that creating a Parsons Table from a list of dictionaries must take some sort of sample of the first x number of dictionaries to determine the columns and if only one dictionary has a column and it's buried deep in the list it does not get sampled.

Two likely solutions would 1. be able to specify in Table how many rows to sample or 2. have some lines in this specific Airtable method that figures out what all the fields are and fills out all the dictionaries so they all have the same number of items.

**Comment by bzupnick** [comment]
I was able to successfully replicate this bug.

I created my own table with 1512 records and 2 columns; `name` and `notes`. 

I found the magic number. If there's a `note` on or below row 445, then `notes` exists in all the later rows. If there are no notes on or below row 445, then the bug is reproduced. 

I don't fully understand why yet. I've been focussing on `petl.io.json.iterdicts` which takes in `sample` and sends it to `iterpeek`. When debugging, `sample` is 1000 so I'm not sure why the magic number is still 445 but I still think that's a viable suspect for where our problem is.

**Comment by bzupnick** [comment]
Docs I foudn in `petl.io.json`:

> If no `header` is specified, fields will be discovered by sampling keys
    from the first `sample` objects in `source`. The header will be
    constructed from keys in the order discovered. Note that this
    ordering may not be stable, and therefore it may be advisable to specify
    an explicit `header` or to use another function like
    :func:`petl.transform.headers.sortheader` on the resulting table to
    guarantee stability.

Again, such that this is the issue is unconfirmed. Assuming it is, though, I see 2 solutions:

1. give the `header` manually. 
2. Make the `sample` larger. 

Obviously option 1 is best for both stability and efficiency, but as I'm only on this project all of 1 day, I'm not yet confident enough to know if option 1 is possible. 

I'll keep digging!

**Comment by bzupnick** [comment]
the order in which the the `petl` table is created is NOT the same order of the Airtable rows. I'm not sure what determines the order but it IS constant. This answers my question of "why row 446 if the `sample` is 1000" because Airtable row `445` translates to the 615th row given to `petl` where as Airtable row 446 translates to the 1346th row given to `petl`. 

That seems to confirm what I thought the issue was and leaves the above 2 options as what I see as the viable options.

**Comment by mkwoods927** [comment]
@bzupnick  Thank you so much for diving into this and getting a resolution in so quickly! Much appreciated.
